### ISSUE TITLE
Timeout Handler has been configured with the incorrect command as `--get` instead of `--timeout` 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/helm#108]
**Summary**:

Timeout Handler has been configured with the incorrect command as `--get` instead of `--timeout` as per the following file:

https://github.com/mojaloop/helm/blob/master/centralledger/chart-handler-timeout/values.yaml

Which contains the following cmd:
`command: '["node", "src/handlers/index.js", "handler", "--get"]'`

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**

File config:
https://github.com/mojaloop/helm/blob/master/centralledger/chart-handler-timeout/values.yaml

Must contains the following cmd:
`command: '["node", "src/handlers/index.js", "handler", "--timeout"]'`

**Steps to Reproduce**
  1. Deploy helm chart

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened: High
- Priority when opened: Medium

**Comment by elnyry** [comment]
Fixed - PR: https://github.com/mojaloop/helm/pull/109
