### ISSUE TITLE
Helm charts incompatible with Kubernetes v1.16.x

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/helm#219]
**Summary**:
Helm charts may be incompatible with Kubernetes v1.16.x due to deprecated APIs as per the following link: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

The following resource kinds will need to be migrated:
- NetworkPolicy (in the extensions/v1beta1 API group)
    Migrate to use the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved/updated via the networking.k8s.io/v1 API.
- PodSecurityPolicy (in the extensions/v1beta1 API group)
    Migrate to use the policy/v1beta1 API, available since v1.10. Existing persisted data can be retrieved/updated via the policy/v1beta1 API.
- DaemonSet, Deployment, StatefulSet, and ReplicaSet (in the extensions/v1beta1 and apps/v1beta2 API groups)
    Migrate to use the apps/v1 API, available since v1.9. Existing persisted data can be retrieved/updated via the apps/v1 API.

The following resource kinds need to be maintained:
- Ingress (in the extensions/v1beta1 API group) SHOULD NOT be upgraded at this time since it will impact backward compatibility < 1.14.x. This will need to be migrated at a later point once v1.20.x reaches critical mass.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

Deployments should be successful on v1.16x, v1.15x, v1.14x and v1.11x

**Steps to Reproduce**
  1. Deploy Mojaloop Helm chart to v1.16.x Kubernetes cluster

**Specifications**
  - Component (if known): Mojaloop Helm Charts
  - Version: v8.x.x
  - Platform: Helm
  - Subsystem: n/a
  - Type of testing: Manual
  - Bug found/raised by: @vijayg10 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical
- Fixes should be tested against Kubernetes v1.11.x, v1.14 & v1.15.x to ensure backward compatibility,
- Alternatively, there will need to be a config param that sets the `apiVersion` appropriately for backward compatibility to be maintained, assuming the update apiVersion in v1.16.x is not supported in v.15.x

**Comment by mdebarros** [comment]
I think we need to possibly include versions 1.17-1.18 for testing. Or at least pick up an issues that need to be further resolved going forward.

**Comment by lewisdaly** [comment]
I think @tdaly61 might be taking this one up. I'll assign him once he's accepted the github invite.

**Comment by tdaly61** [comment]
happy to take it ..please assign

**Comment by lewisdaly** [comment]
Looks like we might have issues with `percona-xtradb-cluster`. From what I've seen so far, the latest version `1.0.3` was last updated a year ago, and requires the old beta apis.

https://github.com/helm/charts/tree/master/stable/percona-xtradb-cluster

**Comment by lewisdaly** [comment]
Specifically, it requires the `StatefulSet` resource at `apiVersion: apps/v1beta2`:

https://github.com/helm/charts/blob/master/stable/percona-xtradb-cluster/templates/statefulset.yaml

**Comment by lewisdaly** [comment]
https://github.com/helm/charts/issues/19697
https://github.com/helm/charts/issues/21538

**Comment by lewisdaly** [comment]
The following (very rough) Draft PR (based on the helm3 changes) is working for kubernetes v1.17: https://github.com/vessels-tech/helm/tree/fix/219-kubernetes-17

**Comment by tdaly61** [comment]
> The following (very rough) Draft PR (based on the helm3 changes) is working for kubernetes v1.17: https://github.com/vessels-tech/helm/tree/fix/219-kubernetes-17

Also I have it running on microk8s v.1.8 , I have data loading without error but there "appear" to be some issues with the Golden_Path tests. I am not familiar enough yet with the application to know how to debug this, and I think @lewisdaly will look at it in the near term with me.

**Comment by lewisdaly** [comment]
It looks like there is a PR in progress for the percona charts: https://github.com/helm/charts/pull/22236

**Comment by mdebarros** [comment]
> helm/charts#22236

It was merged 10 days ago! \:D/

**Comment by mdebarros** [comment]
The issue has been solved in master branch with the following PR: https://github.com/mojaloop/helm/pull/349

It will be included as part of the release v11.x of the Mojaloop Helm Charts.
