### ISSUE TITLE
change all boolean checks to use boolean values as opposed to strings

### ISSUE THREAD

**Issue by dfry** [mojaloop/helm#296]
Regarding the `mojaloop-simulator` helm chart:

Doing string comparisons for boolean values is not compatible with Terraform since when setting values to true or false (or TRUE or FALSE), terraform automatically casts them to booleans which results in failure for the following string comparison:

{{- if eq ($config.config.schemeAdapter.env.JWS_SIGN | upper) "TRUE" }}

Please convert all these values that should be booleans into actual booleans and change the conditionals to just check the value: {{- if $config.config.schemeAdapter.env.JWS_SIGN }}

I haven't done a thorough check but it is happening at least in the secrets.yaml and config-jws-public-keys.yaml

Also, true in quotes is being used in the values files, not sure if this is really needed anywhere, ideally they should be unquoted booleans.

**Comment by msk-** [comment]
@dfry you might like to watch #303

**Comment by mdebarros** [comment]
@dfry @msk- is this still an issue?

**Comment by msk-** [comment]
I believe it's resolved by #303. I'll close. Can reopen if there are problems in future.
