### ISSUE TITLE
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "" ...

### ISSUE THREAD

**Issue by vorburger** [mojaloop/helm#341]
Does anyone know what could cause this error:

```
$ helm --namespace demo --name moja install mojaloop/mojaloop
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1"]
```

I'm getting this when following https://docs.mojaloop.io/documentation/deployment-guide/ - both with Helm v2 as currently documented, as well as when following the v3 doc coming up on https://github.com/mojaloop/documentation/pull/236.

I'm not using _microk8s_ but _minikube_  (currently v1.11.0), but (I'm hoping that) shouldn't matter here, given that doc sounds like it should work on any Kube distro?  Do the Mojaloop charts perhaps only work with a more specific Kube version, and I'm on a too new one? If you suspect that could be it, please clarify which Kube version ya' all are using, and can re-try with that (and if that's it, clarify this with a PR to the doc).

Full disclosure: I a complete noob to Helm (but I more or less know my way around core Kubernetes).

**Comment by lewisdaly** [comment]
Hey @vorburger this is related to #219 

We are using Kubernetes 1.15 for the most part - and the issues you are encountering are related to this: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

There’s a couple workarounds for now:
- 1. Use my temporary branch: https://github.com/vessels-tech/helm/tree/fix/219-kubernetes-17-helm2-2
- 2. You can export the charts from helm as yaml, and then run a few find and replaces to remove the outdated api tags (I haven't done this myself, but I have heard that someone in the community has.

**Comment by vorburger** [comment]
Thanks! I'd rather stick to "pure upstream" - and contribute to this repo to make this easier... I'm happy to use an older Kube, for now.

Indeed with Kubernetes 1.15.12 the problem above is solved - so let me close this.

#347 has some follow-up to make this easier / clearer for the next person coming along.
