### ISSUE TITLE
Install.sh script?

### ISSUE THREAD

**Issue by vorburger** [mojaloop/helm#342]
How about "scripting" https://docs.mojaloop.io/documentation/deployment-guide/#4-helm and https://docs.mojaloop.io/documentation/deployment-guide/#5-mojaloop ? 

I'm thinking nothing fancy, just a good ol' bash script... and then put that into the root of this repo, and simplify the Deployment Guide to "run this script" instead of those ca. 10 manual steps.

This would also make "testing" something like https://github.com/mojaloop/documentation/pull/236/ easier - one would just run this new script to see if it works.

I'm willing to contribute to the project and raise a PR for this, if this seems useful to you? I just need to first be able to get it running manually - I'm currently stuck at #341.

PS: Perhaps this could even be the beginning of more fancy automated test of these Helm charts (in a next step)? Like a `./test.sh` which calls this script but also creates a completely clean new Kube env from scratch and see if everything works. Then we can hook that up to check for each PR.

**Comment by lewisdaly** [comment]
Hi @vorburger this would be amazing. In fact, @tdaly61 and I have been working on https://github.com/tdaly61/mini-loop, which contains pretty much the scripts you are looking for, which some hacks to get around the issues with older kubernetes versions. (Take a look [here](https://github.com/tdaly61/mini-loop/tree/master/scripts))

**Comment by vorburger** [comment]
> creates a completely clean new Kube env from scratch and see if everything works

I'll finish turning https://github.com/mojaloop/helm/compare/master...vorburger:minishift into such a PR after #348 is merged.

**Comment by tdaly61** [comment]
Hi  @vorburger , hey I am sort of following the idea here but not entirely sure.
So are you implementing the same functionality as mini-loop but eliminating the VM is that the purpose ? 
Did you note that mini-loop works for VBox and to GCS (almost) identically ?
Perhaps what I am wondering and this is  to you and @lewisdaly is does what you are doing here obviate mini-loop efforts or somehow do they complement each other ?  cheers and thanks

**Comment by tdaly61** [comment]
Ok I took ownership of this and have essentially implemented it in the form of mini-loop.  I intended to make a pull request shortly and seek to move the main mini-loop functions into the helm charts under a /install directory
