### ISSUE TITLE
Kubernetes Version constraint (kubeVersion)

### ISSUE THREAD

**Issue by vorburger** [mojaloop/helm#347]
I've learnt in #341 that the Mojaloop Helm charts are currently fairly picky about the Kubernetes versions.

I understand that efforts such as #219 are under way to make it compatible with more recent versions, but it seems to me that the project could lower its barrier to entry by a) having a line about required versions in its doc, and b) making the Helm charts "fail fast & early" on unsupported Kubernetes versions?

I'll raise a PR for a) the doc ASAP. For b) my Helm Foo isn't good enough yet, but as I learn, I'll contribute - or someone else can before me.

**Comment by vorburger** [comment]
> making the Helm charts "fail fast & early" on unsupported Kubernetes versions?

https://helm.sh/docs/topics/charts/#the-kubeversion-field seems to permit doing this kind of thing? (I need to try (and first properly script, see #342) how to https://github.com/mojaloop/helm#deployment-from-source-for-local-repo-deployments before I can contribute that).

**Comment by lewisdaly** [comment]
Thanks for this @vorburger .

I know @mdebarros is doing some work in this on: https://github.com/mojaloop/project/issues/1463, so perhaps he might be able to offer some advice, or we should at least make sure we're not duplicating effort here.

**Comment by lewisdaly** [comment]
> https://helm.sh/docs/topics/charts/#the-kubeversion-field seems to permit doing this kind of thing? 

Looks like there is a PR in the works for this https://github.com/mojaloop/helm/pull/349

**Comment by mdebarros** [comment]
PR https://github.com/mojaloop/helm/pull/349 resolves this issue. This will be publically available shortly in release v11.0.0.
