### ISSUE TITLE
ingress-nginx chart from upstream instead of mojaloop/helm/kube-public/ingress-nginx

### ISSUE THREAD

**Issue by vorburger** [mojaloop/helm#350]
https://github.com/mojaloop/helm/tree/master/kube-public/ingress-nginx could perhaps be replaced with the "official" one?

* https://kubernetes.github.io/ingress-nginx/deploy/#using-helm
* https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/
* https://github.com/helm/charts/tree/master/stable/nginx-ingress

Probably just means `git rm -r kube-public/ingress-nginx` and updating https://docs.mojaloop.io/documentation/deployment-guide/#41-helm-configuration ?  (Haven't tested it.)

**Comment by vorburger** [comment]
Actually, hang on... the documented (Deployment Guide) `helm --namespace kube-public install stable/nginx-ingress` anyway is already installing that "official" one, right? So what if anything still uses that `mojaloop/helm/kube-public/ingress-nginx` - can we just delete it without breaking anything?

**Comment by vorburger** [comment]
Oh https://github.com/mojaloop/helm#deployment-from-source-for-local-repo-deployments README still mentions `helm install ./kube-public/ingress-nginx` - perhaps we can just change that to be consistent with the Deployment Guide, and then remove it?

**Comment by mdebarros** [comment]
> Actually, hang on... the documented (Deployment Guide) `helm --namespace kube-public install stable/nginx-ingress` anyway is already installing that "official" one, right? So what if anything still uses that `mojaloop/helm/kube-public/ingress-nginx` - can we just delete it without breaking anything?

Yeah, we can remove it. There was no official Helm chart at the time when it was introduced.

I will remove it with v11.0.0 release.

**Comment by mdebarros** [comment]
This change will be publically available in release v11.0.0 --> https://github.com/mojaloop/helm/pull/401
