### ISSUE TITLE
Helm chart requirements dependencies are disabled for all child and parent charts when disabled.

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/helm#54]
## Scenario
Helm chart requirements dependencies are disabled for all child and parent charts when disabled. 

## Issue
E.g. When disabling the Postgres server on the Central-Ledger, all Postgres dependencies are disabled through-out (Parent, Sister, Children, etc) all the Helm charts.

## Fix
Need to investigate a solution and/or possible open a bug with the Helm team.

**Comment by lewisdaly** [comment]
@mdebarros is this still an issue? Looks like this may be a little out of date
